## How to Use
##
## $ python char_funcs_tbl.py > char_funcs_tbl.h
##

import sys

symbol  = 0x01
initial = 0x02
delimit = 0x04

symbol_chars    = map(ord, ".!?*+-/:<=>$%&@^_~")
initial_chars   = map(ord, "!?*/:<=>$%&^_~")
delimiter_chars = map(ord, "()[]\";#")

tbl = []
for i in range(128):
    x = 0
    x |= symbol  if (chr(i).isalnum() or i in symbol_chars)  else 0
    x |= initial if (chr(i).isalpha() or i in initial_chars) else 0
    x |= delimit if i in delimiter_chars                   else 0
    tbl.append(x)

sys.stdout.write("""/***

   !!! DON'T EDIT THIS FILE !!!
   !!! This file is generated by char_funcs_tbl.py !!!

***/

const uint8_t g_char_funcs_tbl[128] = {""" + ",".join(map(hex, tbl)) + """};

#define SYMBOL_CHARP(x)     ((g_char_funcs_tbl[x] & """ + hex(symbol)  + """) != 0)
#define INITIAL_CHARP(x)    ((g_char_funcs_tbl[x] & """ + hex(initial) + """) != 0)
#define DELIMITER_CHARP(x)  ((g_char_funcs_tbl[x] & """ + hex(delimit) + """) != 0)

""")
