#!/bin/bash

NAME="Glaze-Arc"
VERSION="0.2.0"
LAST_COMMIT=`git log -1 --format="%cd"`

cat <<EOF
#ifndef VERSION_H_
#define VERSION_H_

#include <stdio.h>

/// !! Generated by 'genver.sh' DON'T EDIT !! ///

// The name of this program.
const char * program_name = "$NAME";
// The version of this program.
const char * version = "$VERSION";
// The last commit date time.
const char * last_commit_date = "$LAST_COMMIT";

// Print an ID stamp for the program.
int _program_id_stamp(FILE* output)
{
    fprintf (output, "%s version %s (%s) compiled at %s %s\n",
             program_name, version, last_commit_date, __DATE__, __TIME__ );

    return 0;
}

#endif /* VERSION_H_ */
EOF